
# Variables
GCC = gcc
FLAGS =
PROGRAMAS = ejercicio01 ejercicio02 ejercicio03 ejercicio04 ejercicio05 ejercicio06 ejercicio07 ejercicio08

# Reglas para compilar cada programa
ejercicio01:
	$(GCC) $(FLAGS) ejercicio01.c -o ejercicio01

ejercicio02:
	$(GCC) $(FLAGS) ejercicio02.c -o ejercicio02

ejercicio03:
	$(GCC) $(FLAGS) ejercicio03.c -o ejercicio03

ejercicio04:
	$(GCC) $(FLAGS) ejercicio04.c -o ejercicio04

ejercicio05:
	$(GCC) $(FLAGS) ejercicio05.c -o ejercicio05

ejercicio06:
	$(GCC) $(FLAGS) ejercicio06.c -o ejercicio06

ejercicio07:
	$(GCC) $(FLAGS) ejercicio07.c -o ejercicio07

ejercicio08:
	$(GCC) $(FLAGS) ejercicio08.c -o ejercicio08

# Regla para limpiar todos los ejecutables
clean:
	$(RM) $(PROGRAMAS)

