GCC = gcc
FLAGS = -Wall -g

PROGRAMAS = labFichero01 labFichero02 labFichero03

labFichero01:
	$(GCC) $@.c -o $@
labFichero02:
	$(GCC) $@.c -o $@
labFichero03:
	$(GCC) $@.c -o $@
clear:
	$(RM) $(PROGRAMAS)
