#************************************************************
#Autor: Christian David Becerra Enciso
#Asignatura: Sistemas Operativos
#Docente: J.Corredor
#Fecha: 11/11/20
#
# ======> Makefile para automatizacion de los 6 ficheros 
#
#####################################################################
GCC = gcc
FLAGS = -lm -fopenmp

PROGRAMAS = labOpenMP01 labOpenMP02 labOpenMP03 labOpenMP04 labOpenMP05 labOpenMP06

labOpenMP01:
	$(GCC) $@.c -o $@ $(FLAGS)
labOpenMP02:
	$(GCC) $@.c -o $@ $(FLAGS)
labOpenMP03:
	$(GCC) $@.c -o $@ $(FLAGS)
labOpenMP04:
	$(GCC) $@.c -o $@ $(FLAGS)
labOpenMP05:
	$(GCC) $@.c -o $@ $(FLAGS)
labOpenMP06:
	$(GCC) $@.c -o $@ $(FLAGS)
clear:
	$(RM) $(PROGRAMAS)
